/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.view.arquivo;

import javax.swing.JTree;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreeSelectionModel;

/**
 *
 * @author root
 */
public class FrmMapaAcervo extends javax.swing.JInternalFrame implements TreeSelectionListener {

    JTree jTreeDados;
    
    /**
     * Creates new form FrmMapaAcervo
     */
    public FrmMapaAcervo() {
        initComponents();
        carregaDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldSelecionado = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Mapa Acervo");

        jTextFieldSelecionado.setEditable(false);
        jTextFieldSelecionado.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldSelecionado, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextFieldSelecionado;
    // End of variables declaration//GEN-END:variables

    private void carregaDados() {
        // Adiciona o elemento filho de root com 3 filhos
        DefaultMutableTreeNode defaultMutableTreeNodeProgramacao = new DefaultMutableTreeNode("Programação");
        DefaultMutableTreeNode defaultMutableTreeNodeJava = new DefaultMutableTreeNode("Java");
        DefaultMutableTreeNode defaultMutableTreeNodePython = new DefaultMutableTreeNode("Python");
        // Adiciona os subelementos
        defaultMutableTreeNodeJava.add(new DefaultMutableTreeNode("Java - Como Programar"));
        defaultMutableTreeNodePython.add(new DefaultMutableTreeNode("Python do básico ao avançado"));
        defaultMutableTreeNodeProgramacao.add(defaultMutableTreeNodeJava);
        defaultMutableTreeNodeProgramacao.add(defaultMutableTreeNodePython);
        
        // Adiciona outro subelemento de root com 3 filhos
        DefaultMutableTreeNode defaultMutableTreeNodeAnaliseSistemas = new DefaultMutableTreeNode("Análise de Sistemas");
        // Adiciona os subelementos
        defaultMutableTreeNodeAnaliseSistemas.add(new DefaultMutableTreeNode("Introdução à modelagem de Sistemas"));
        
        // Cria o elemento root e adiciona os DefaultMutableTreeNode filhos criados anteriormente
        DefaultMutableTreeNode defaultMutableTreeNodeBiblioteca = new DefaultMutableTreeNode("Biblioteca");
        // Adiciona os DefaultMutableTreeNode filhos no elemento root
        defaultMutableTreeNodeBiblioteca.add(defaultMutableTreeNodeProgramacao);
        defaultMutableTreeNodeBiblioteca.add(defaultMutableTreeNodeAnaliseSistemas);
        
        // Instância o componente JTree passando para o construtor o DefaultMutableTreeNode root
        jTreeDados = new JTree(defaultMutableTreeNodeBiblioteca);
        // Adiciona o para o componente o evento que deve ser executando quando for selecionado um elemento final
        jTreeDados.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        jTreeDados.addTreeSelectionListener(this);
        // Atribui o tamanho do componente de 200 por 200 pixel
        jTreeDados.setSize(200, 200);
        jTreeDados.setLocation(10, 40);
        jTreeDados.setAutoscrolls(true);
        
        // Estiliza a forma de apresentar as pastinhas no componente
//        jTreeDados.putClientProperty("JTree.lineStyle", "Angled"); // Linhas  (default)
//        jTreeDados.putClientProperty("JTree.lineStyle", "Horizontal"); // Linhas Horizontal
//        jTreeDados.putClientProperty("JTree.lineStyle", "None"); // Nenhuma linha
        
        // Adiciona o componente na tela do formulário
        this.add(jTreeDados);
    }

    @Override
    public void valueChanged(TreeSelectionEvent e) {
        // Recupera o elemento selecionado
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) jTreeDados.getLastSelectedPathComponent();
 
        // Efetua o teste se o componente não é nulo
        if (node == null) {
            // Caso for nulo retorna o método
            return;
        }
 
        // Recupera o objeto do elemento 
        Object nodeInfo = node.getUserObject();
        
        // Efetua teste se o componente não tem mais filhos e é um elemento final
        if (node.isLeaf()) {
            // Apresenta o nome do elemento no campo de texto
            jTextFieldSelecionado.setText(nodeInfo.toString());
        }
    }
}
