/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.view.cadastro;

import br.edu.utfpr.entity.Biblioteca;
import br.edu.utfpr.util.FileUtil;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class FrmCadastroBiblioteca extends javax.swing.JInternalFrame {

    private Biblioteca biblioteca;
    
    /**
     * Creates new form FrmCadastroBiblioteca
     */
    public FrmCadastroBiblioteca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelQuantidadeLivros = new javax.swing.JLabel();
        jTextFieldQuantidadeLivros = new javax.swing.JTextField();
        jLabelQuantidadePrateleiras = new javax.swing.JLabel();
        jTextFieldQuantidadePrateleiras = new javax.swing.JTextField();
        jButtonGravar = new javax.swing.JButton();
        jButtonGravarArquivo = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro Biblioteca");

        jLabelNome.setText("Nome");

        jLabelQuantidadeLivros.setText("Quantidade Livros");

        jLabelQuantidadePrateleiras.setText("Quantidade Prateleiras");

        jButtonGravar.setText("Gravar");
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });

        jButtonGravarArquivo.setText("Gravar Arquivo");
        jButtonGravarArquivo.setEnabled(false);
        jButtonGravarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarArquivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGravarArquivo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelQuantidadeLivros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQuantidadeLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLabelQuantidadePrateleiras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldQuantidadePrateleiras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldQuantidadeLivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelQuantidadeLivros)
                    .addComponent(jTextFieldQuantidadePrateleiras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelQuantidadePrateleiras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGravar)
                    .addComponent(jButtonGravarArquivo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        // TODO add your handling code here:
        onClickedGravar();
    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jButtonGravarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarArquivoActionPerformed
        // TODO add your handling code here:
        onClickedGravarArquivo();
    }//GEN-LAST:event_jButtonGravarArquivoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonGravarArquivo;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelQuantidadeLivros;
    private javax.swing.JLabel jLabelQuantidadePrateleiras;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldQuantidadeLivros;
    private javax.swing.JTextField jTextFieldQuantidadePrateleiras;
    // End of variables declaration//GEN-END:variables

    private void onClickedGravar() {
        biblioteca = new Biblioteca();
        
        biblioteca.setNome(jTextFieldNome.getText());
        biblioteca.setQuantidadeLivros(Integer.parseInt(jTextFieldQuantidadeLivros.getText()));
        biblioteca.setQuantidadePrateleiras(Integer.parseInt(jTextFieldQuantidadePrateleiras.getText()));
        
        limparCampos();
        
        jButtonGravarArquivo.setEnabled(true);
        
        JOptionPane.showMessageDialog(this, "Dados gravados com sucesso!");
    }
    
    private void limparCampos() {
        jTextFieldNome.setText("");
        jTextFieldQuantidadeLivros.setText("");
        jTextFieldQuantidadePrateleiras.setText("");
    }

    private void onClickedGravarArquivo() {
        StringBuilder dados = new StringBuilder();
        
        dados.append("Nome: ").append(biblioteca.getNome()).append("\n");
        dados.append("Quantidade Livros: ").append(biblioteca.getQuantidadeLivros()).append("\n");
        dados.append("Quantidade Prateleiras: ").append(biblioteca.getQuantidadePrateleiras()).append("\n");
        
        FileUtil.gravarDadosTXT(dados.toString());
        
        JOptionPane.showMessageDialog(this, "Dados gravados no arquivo com sucesso!");
    }
}
