/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.view.cadastro;

import br.edu.utfpr.model.entity.Cliente;
import br.edu.utfpr.util.FileUtil;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.OutputStream;

/**
 *
 * @author root
 */
public class FrmCadastroArquivo extends javax.swing.JInternalFrame {

    private Cliente cliente;
    
    /**
     * Creates new form FrmCadastroArquivo
     */
    public FrmCadastroArquivo() {
        initComponents();
        cliente = new Cliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabelEndereco = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonGravarTXT = new javax.swing.JButton();
        jButtonGravarBIN = new javax.swing.JButton();
        jButtonGravarDB = new javax.swing.JButton();
        jButtonGravarCSV = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Cadastro Arquivo");

        jLabelNome.setText("Nome");

        jLabelEndereco.setText("Endereço");

        jLabelEmail.setText("E-mail");

        jButtonGravarTXT.setText("Gravar TXT");
        jButtonGravarTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarTXTActionPerformed(evt);
            }
        });

        jButtonGravarBIN.setText("Gravar BIN");
        jButtonGravarBIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarBINActionPerformed(evt);
            }
        });

        jButtonGravarDB.setText("Gravar DB");
        jButtonGravarDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarDBActionPerformed(evt);
            }
        });

        jButtonGravarCSV.setText("Gravar CSV");
        jButtonGravarCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarCSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonGravarTXT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGravarBIN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGravarDB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGravarCSV)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEndereco)
                            .addComponent(jLabelEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNome, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEmail)
                            .addComponent(jTextFieldNome)
                            .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEndereco)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGravarTXT)
                    .addComponent(jButtonGravarBIN)
                    .addComponent(jButtonGravarDB)
                    .addComponent(jButtonGravarCSV))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGravarTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarTXTActionPerformed
        // TODO add your handling code here:
        onClickedGravarTXT();
    }//GEN-LAST:event_jButtonGravarTXTActionPerformed

    private void jButtonGravarBINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarBINActionPerformed
        // TODO add your handling code here:
        onClickedGravarBIN();
    }//GEN-LAST:event_jButtonGravarBINActionPerformed

    private void jButtonGravarDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarDBActionPerformed
        // TODO add your handling code here:
        onClickedGravarDB();
    }//GEN-LAST:event_jButtonGravarDBActionPerformed

    private void jButtonGravarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarCSVActionPerformed
        // TODO add your handling code here:
        onClickedGravarCSV();
    }//GEN-LAST:event_jButtonGravarCSVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGravarBIN;
    private javax.swing.JButton jButtonGravarCSV;
    private javax.swing.JButton jButtonGravarDB;
    private javax.swing.JButton jButtonGravarTXT;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables

    private void onClickedGravarTXT() {
        setCliente();
        FileUtil.gravarDadosTXT(getCliente());
    }

    private void onClickedGravarBIN() {
        setCliente();
        FileUtil.gravarDadosBIN(getCliente());
    }

    private void onClickedGravarDB() {
        setCliente();
        FileUtil.gravarDadoDB(getCliente());
    }

    private void onClickedGravarCSV() {
        setCliente();
        FileUtil.gravarDadosCSV(getCliente());
    }
    
    private void setCliente() {
        cliente.setNome(jTextFieldNome.getText());
        cliente.setEndereco(jTextFieldEndereco.getText());
        cliente.setEmail(jTextFieldEmail.getText());
    }
    
    private String getCliente() {
        StringBuilder toReturn = new StringBuilder();
        toReturn.append("Nome=").append(cliente.getNome()).append("\n");
        toReturn.append("Endereço=").append(cliente.getEndereco()).append("\n");
        toReturn.append("E-mail=").append(cliente.getEmail()).append("\n");
        
        return toReturn.toString();
    }
    

}
