/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.view.cadastro;

import br.edu.utfpr.model.entity.Cliente;
import br.edu.utfpr.util.FileUtil;

/**
 *
 * @author root
 */
public class FrmCadastroArquivo extends javax.swing.JInternalFrame {

    private Cliente cliente;
    
    /**
     * Creates new form FrmCadastroArquivo
     */
    public FrmCadastroArquivo() {
        initComponents();
        cliente = new Cliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabelEndereco = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonGravarTXT = new javax.swing.JButton();
        jButtonGravarBIN = new javax.swing.JButton();
        jButtonGravarDAT = new javax.swing.JButton();
        jButtonGravarCSV = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonLerTXT = new javax.swing.JButton();
        jButtonLerBIN = new javax.swing.JButton();
        jButtonLerDAT = new javax.swing.JButton();
        jButtonLerCSV = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Cadastro Arquivo");

        jLabelNome.setText("Nome");

        jLabelEndereco.setText("Endereço");

        jLabelEmail.setText("E-mail");

        jButtonGravarTXT.setText("Gravar TXT");
        jButtonGravarTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarTXTActionPerformed(evt);
            }
        });

        jButtonGravarBIN.setText("Gravar BIN");
        jButtonGravarBIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarBINActionPerformed(evt);
            }
        });

        jButtonGravarDAT.setText("Gravar DAT");
        jButtonGravarDAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarDATActionPerformed(evt);
            }
        });

        jButtonGravarCSV.setText("Gravar CSV");
        jButtonGravarCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarCSVActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonLerTXT.setText("Ler TXT");
        jButtonLerTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLerTXTActionPerformed(evt);
            }
        });

        jButtonLerBIN.setText("Ler BIN");
        jButtonLerBIN.setActionCommand("Ler BIN");
        jButtonLerBIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLerBINActionPerformed(evt);
            }
        });

        jButtonLerDAT.setText("Ler DAT");
        jButtonLerDAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLerDATActionPerformed(evt);
            }
        });

        jButtonLerCSV.setText("Ler CSV");
        jButtonLerCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLerCSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEndereco)
                            .addComponent(jLabelEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNome, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEmail)
                            .addComponent(jTextFieldNome)
                            .addComponent(jTextFieldEndereco)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonGravarTXT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGravarBIN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGravarDAT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGravarCSV, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonLerTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLerBIN, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLerDAT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLerCSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEndereco)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGravarTXT)
                    .addComponent(jButtonGravarBIN)
                    .addComponent(jButtonGravarDAT)
                    .addComponent(jButtonGravarCSV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLerTXT)
                    .addComponent(jButtonLerBIN)
                    .addComponent(jButtonLerDAT)
                    .addComponent(jButtonLerCSV))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGravarTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarTXTActionPerformed
        // TODO add your handling code here:
        onClickedGravarTXT();
    }//GEN-LAST:event_jButtonGravarTXTActionPerformed

    private void jButtonGravarBINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarBINActionPerformed
        // TODO add your handling code here:
        onClickedGravarBIN();
    }//GEN-LAST:event_jButtonGravarBINActionPerformed

    private void jButtonGravarDATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarDATActionPerformed
        // TODO add your handling code here:
        onClickedGravarDB();
    }//GEN-LAST:event_jButtonGravarDATActionPerformed

    private void jButtonGravarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarCSVActionPerformed
        // TODO add your handling code here:
        onClickedGravarCSV();
    }//GEN-LAST:event_jButtonGravarCSVActionPerformed

    private void jButtonLerTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLerTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLerTXTActionPerformed

    private void jButtonLerBINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLerBINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLerBINActionPerformed

    private void jButtonLerDATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLerDATActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLerDATActionPerformed

    private void jButtonLerCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLerCSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLerCSVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGravarBIN;
    private javax.swing.JButton jButtonGravarCSV;
    private javax.swing.JButton jButtonGravarDAT;
    private javax.swing.JButton jButtonGravarTXT;
    private javax.swing.JButton jButtonLerBIN;
    private javax.swing.JButton jButtonLerCSV;
    private javax.swing.JButton jButtonLerDAT;
    private javax.swing.JButton jButtonLerTXT;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables

    private void onClickedGravarTXT() {
        setCliente();
        FileUtil.gravarDadosTXT(getCliente());
    }

    private void onClickedGravarBIN() {
        setCliente();
        FileUtil.gravarDadosBIN(getCliente());
    }

    private void onClickedGravarDB() {
        setCliente();
        FileUtil.gravarDadoDAT(getCliente());
    }

    private void onClickedGravarCSV() {
        setCliente();
        FileUtil.gravarDadosCSV(getCliente());
    }
    
    private void setCliente() {
        cliente.setNome(jTextFieldNome.getText());
        cliente.setEndereco(jTextFieldEndereco.getText());
        cliente.setEmail(jTextFieldEmail.getText());
    }
    
    private String getCliente() {
        StringBuilder toReturn = new StringBuilder();
        toReturn.append("Nome=").append(cliente.getNome()).append("\n");
        toReturn.append("Endereço=").append(cliente.getEndereco()).append("\n");
        toReturn.append("E-mail=").append(cliente.getEmail()).append("\n");
        
        return toReturn.toString();
    }
    

}
